return {
  'NMAC427/guess-indent.nvim',

  { import = 'plugins.telescope' },
  { import = 'plugins.lsp' },
  { import = 'plugins.blink' },
  { import = 'plugins.treesitter' },
  { import = 'plugins.neo-tree' },
  { import = 'plugins.conform' },
  { import = 'plugins.toggleterm' },
  { import = 'plugins.which-key' },
  { import = 'plugins.gitsigns' },
  { import = 'plugins.lualine' },
  { import = 'plugins.bufferline' },
  { import = 'plugins.trouble' },
  { import = 'plugins.flash' },
  { import = 'plugins.mini' },
  { import = 'plugins.colorscheme' },
  { import = 'plugins.todo-comments' },
  { import = 'plugins.noice' },
  { import = 'plugins.notify' },
  { import = 'plugins.dashboard' },
  { import = 'plugins.persistence' },
  { import = 'plugins.project' },
  { import = 'plugins.spectre' },
  { import = 'plugins.comment' },
  { import = 'plugins.codediff' },
  { import = 'plugins.aicommits' },
  { import = 'plugins.snacks' },
  { import = 'plugins.tailwind-tools' },
  { import = 'plugins.colorizer' },
  { import = 'plugins.extra' },
}
