return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    delay = 0,
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ', Down = '<Down> ', Left = '<Left> ', Right = '<Right> ',
        C = '<C-…> ', M = '<M-…> ', D = '<D-…> ', S = '<S-…> ',
        CR = '<CR> ', Esc = '<Esc> ', ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ', NL = '<NL> ', BS = '<BS> ',
        Space = '<Space> ', Tab = '<Tab> ', F1 = '<F1>', F2 = '<F2>',
        F3 = '<F3>', F4 = '<F4>', F5 = '<F5>', F6 = '<F6>',
        F7 = '<F7>', F8 = '<F8>', F9 = '<F9>', F10 = '<F10>',
        F11 = '<F11>', F12 = '<F12>',
      },
    },
    spec = {
      { '<leader>b', group = '[B]uffer' },
      { '<leader>d', group = '[D]ebug' },
      { '<leader>g', group = '[G]it' },
      { '<leader>gd', desc = 'CodeDiff: changes sidebar' },
      { '<leader>gD', desc = 'CodeDiff: history' },
      { '<leader>gf', desc = 'CodeDiff: current file vs HEAD' },
      { '<leader>ga', desc = 'AI commit message' },
      { '<leader>lg', desc = 'Lazygit' },
      { '<leader>uz', desc = 'Zen mode' },
      { '<leader>uy', desc = 'Yank history' },
      { '<leader>um', desc = 'Toggle markdown preview' },
      { '<leader>uD', desc = 'Toggle dim' },
      { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
      { '<leader>l', group = '[L]aravel' },
      { '<leader>ll', desc = 'Laravel: master picker' },
      { '<leader>la', desc = 'Laravel: artisan' },
      { '<leader>lr', desc = 'Laravel: routes' },
      { '<leader>lm', desc = 'Laravel: make' },
      { '<leader>lo', desc = 'Laravel: resources' },
      { '<leader>lt', desc = 'Laravel: code actions' },
      { '<leader>lu', desc = 'Laravel: artisan hub' },
      { '<leader>m', group = '[M]inimap' },
      { '<leader>mm', desc = 'Toggle minimap' },
      { '<leader>n', group = 'T[e]st' },
      { '<leader>nt', desc = 'Test: nearest' },
      { '<leader>nT', desc = 'Test: file' },
      { '<leader>nR', desc = 'Test: all' },
      { '<leader>ns', desc = 'Test: summary' },
      { '<leader>no', desc = 'Test: output' },
      { '<leader>o', group = '[O]utline' },
      { '<leader>p', group = '[P]roject' },
      { '<leader>q', group = '[Q]uit/Session' },
      { '<leader>s', group = '[S]earch' },
      { '<leader>S', group = 'Spectre' },
      { '<leader>t', group = '[T]oggle/Terminal' },
      { '<leader>u', group = '[U]tility' },
      { '<leader>x', group = 'Diagnostics' },
    },
  },
}
