local function vscode_map(mode, lhs, rhs, opts)
  vim.keymap.set(mode, lhs, rhs, opts)
  if vim.g.is_mac then
    local cmd_lhs = lhs:gsub('<C%-', '<D-')
    if cmd_lhs ~= lhs then
      vim.keymap.set(mode, cmd_lhs, rhs, opts)
    end
  end
end

vim.g.is_mac = true
vim.env.PATH = vim.env.PATH .. ':' .. vim.fn.expand('~/.luarocks/bin')

vscode_map('n', '<C-s>', ':w<CR>', { desc = 'Save file' })
vscode_map('i', '<C-s>', '<Esc>:w<CR>a', { desc = 'Save file (insert mode)' })
vscode_map('n', '<C-S-s>', ':wa<CR>', { desc = 'Save all files' })
vscode_map('n', '<C-z>', 'u', { desc = 'Undo' })
vscode_map('i', '<C-z>', '<Esc>ua', { desc = 'Undo (insert mode)' })
vscode_map('n', '<C-y>', '<C-r>', { desc = 'Redo' })
vscode_map('i', '<C-y>', '<Esc><C-r>a', { desc = 'Redo (insert mode)' })
vscode_map('v', '<C-x>', '"+x', { desc = 'Cut' })
vscode_map('v', '<C-c>', '"+y', { desc = 'Copy' })
vscode_map('n', '<C-v>', '"+p', { desc = 'Paste' })
vscode_map('i', '<C-v>', '<C-r>+', { desc = 'Paste (insert mode)' })
vscode_map('c', '<C-v>', '<C-r>+', { desc = 'Paste (command mode)' })
vscode_map('n', '<C-a>', 'ggVG', { desc = 'Select all' })
vscode_map('n', '<C-p>', function()
  require('telescope.builtin').find_files({})
end, { desc = 'Quick Open Files' })
vscode_map('n', '<C-S-p>', function()
  require('telescope.builtin').commands()
end, { desc = 'Command Palette' })
vscode_map('n', '<C-f>', '/', { desc = 'Find in current file' })
vscode_map('v', '<C-f>', '/', { desc = 'Find in current file' })
vscode_map('n', '<C-r>', ':s/', { desc = 'Replace in current file' })
vscode_map('v', '<C-r>', ':s/', { desc = 'Replace in selection' })
vscode_map('n', '<C-S-f>', function()
  require('telescope.builtin').live_grep()
end, { desc = 'Find in Files' })
vscode_map('n', '<C-S-h>', function()
  local ok, spectre = pcall(require, 'spectre')
  if ok then spectre.open() else print('Spectre not available') end
end, { desc = 'Replace in Files' })
vscode_map('n', '<C-g>', ':lua vim.ui.input({prompt="Go to line: "}, function(input) if input then vim.cmd("normal! " .. input .. "G") end end)<CR>', { desc = 'Go to Line' })
vscode_map('n', '<C-S-k>', 'dd', { desc = 'Delete Line' })
vscode_map('i', '<C-S-k>', '<Esc>dda', { desc = 'Delete Line (insert mode)' })
vscode_map('n', '<C-CR>', 'o<Esc>', { desc = 'Insert Line Below' })
vscode_map('i', '<C-CR>', '<Esc>o', { desc = 'Insert Line Below (insert mode)' })
vscode_map('n', '<C-S-CR>', 'O<Esc>', { desc = 'Insert Line Above' })
vscode_map('i', '<C-S-CR>', '<Esc>O', { desc = 'Insert Line Above (insert mode)' })
vscode_map('n', '<C-/>', function()
  local ok, comment_api = pcall(require, 'Comment.api')
  if ok then comment_api.toggle.linewise.current() else vim.cmd('normal gcc') end
end, { desc = 'Toggle Line Comment' })
vscode_map('v', '<C-/>', function()
  local ok, comment_api = pcall(require, 'Comment.api')
  if ok then
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<ESC>', true, false, true), 'nx', false)
    comment_api.toggle.linewise(vim.fn.visualmode())
  else
    vim.cmd("'<,'>normal gcc")
  end
end, { desc = 'Toggle Line Comment' })
vscode_map('n', '<C-]>', '>>', { desc = 'Indent Line' })
vscode_map('n', '<C-[>', '<<', { desc = 'Outdent Line' })
vscode_map('v', '<C-]>', '>gv', { desc = 'Indent Selection' })
vscode_map('v', '<C-[>', '<gv', { desc = 'Outdent Selection' })
vscode_map('n', '<C-Tab>', ':bnext<CR>', { desc = 'Next Editor' })
vscode_map('n', '<C-S-Tab>', ':bprevious<CR>', { desc = 'Previous Editor' })
vscode_map('n', '<C-S-w>', ':bd<CR>', { desc = 'Close Editor' })
vscode_map('n', '<C-S-n>', ':tabnew<CR>', { desc = 'New Window' })
vscode_map('n', '<C-S-t>', ':e #<CR>', { desc = 'Reopen Last Closed Editor' })
vscode_map('n', '<C-S-`>', function()
  local ok, _ = pcall(require, 'toggleterm')
  if ok then vim.cmd('ToggleTerm direction=horizontal') else vim.cmd('split | terminal | resize 15') end
end, { desc = 'New Terminal' })
vscode_map('n', '<F2>', vim.lsp.buf.rename, { desc = 'Rename Symbol' })
vscode_map('n', '<F12>', vim.lsp.buf.definition, { desc = 'Go to Definition' })
vscode_map('n', '<S-F12>', function()
  require('telescope.builtin').lsp_references()
end, { desc = 'Find All References' })
vscode_map('n', '<C-t>', function()
  require('telescope.builtin').lsp_workspace_symbols()
end, { desc = 'Go to Symbol in Workspace' })
vscode_map('n', '<C-S-m>', function()
  local ok, trouble = pcall(require, 'trouble')
  if ok then vim.cmd('Trouble diagnostics toggle') else require('telescope.builtin').diagnostics() end
end, { desc = 'Show Problems' })
vscode_map('n', '<A-S-f>', function()
  require('conform').format({ async = true, lsp_format = 'fallback' })
end, { desc = 'Format Document' })
vscode_map('n', '<A-F12>', function()
  local params = vim.lsp.util.make_position_params()
  vim.lsp.buf_request(0, 'textDocument/definition', params, function(err, result)
    if result and #result > 0 then vim.lsp.util.preview_location(result[1], { border = 'rounded' }) end
  end)
end, { desc = 'Peek Definition' })
vscode_map('n', '<C-.>', vim.lsp.buf.code_action, { desc = 'Quick Fix' })
vscode_map('n', '<F8>', vim.diagnostic.goto_next, { desc = 'Next Problem' })
vscode_map('n', '<S-F8>', vim.diagnostic.goto_prev, { desc = 'Previous Problem' })
vscode_map('n', '<C-\\>', ':vs<CR>', { desc = 'Split Editor Right' })
vscode_map('n', '<C-0>', function()
  local ok = pcall(vim.cmd, 'Neotree focus')
  if not ok then pcall(vim.cmd, 'Neotree show') end
end, { desc = 'Focus Sidebar (Explorer)' })
vscode_map('n', '<C-1>', function()
  local wins = vim.api.nvim_list_wins()
  for _, win in ipairs(wins) do
    local buf = vim.api.nvim_win_get_buf(win)
    local ft = vim.bo[buf].filetype
    local bt = vim.bo[buf].buftype
    if ft ~= 'neo-tree' and ft ~= 'toggleterm' and bt ~= 'nofile' and bt ~= 'terminal' then
      vim.api.nvim_set_current_win(win)
      return
    end
  end
  vim.cmd('wincmd p')
end, { desc = 'Focus Editor' })
vscode_map('n', '<C-S-g>', function()
  local ok, _ = pcall(require, 'neogit')
  if ok then vim.cmd('Neogit') else print('Neogit not available') end
end, { desc = 'Source Control' })
vscode_map('n', '<C-S-o>', function()
  require('telescope.builtin').lsp_workspace_symbols()
end, { desc = 'Go to Symbol in Workspace' })
vscode_map('n', '<C-S-r>', function()
  require('telescope.builtin').oldfiles()
end, { desc = 'Recent Files' })
vscode_map('n', '<A-Up>', ':m .-2<CR>==', { desc = 'Move Line Up' })
vscode_map('n', '<A-Down>', ':m .+1<CR>==', { desc = 'Move Line Down' })
vscode_map('v', '<A-Up>', ":m '<-2<CR>gv=gv", { desc = 'Move Selection Up' })
vscode_map('v', '<A-Down>', ":m '>+1<CR>gv=gv", { desc = 'Move Selection Down' })
vscode_map('n', '<A-z>', function()
  vim.wo.wrap = not vim.wo.wrap
  print('Word wrap: ' .. (vim.wo.wrap and 'enabled' or 'disabled'))
end, { desc = 'Toggle Word Wrap' })
vscode_map('n', '<C-n>', ':enew<CR>', { desc = 'New File' })
vscode_map('n', '<C-,>', function()
  vim.cmd('edit ' .. vim.fn.stdpath('config') .. '/init.lua')
end, { desc = 'Open Settings' })
